//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prModelsParametersOptimization.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRMODELSPARAMETERSESTIMATION_H)
#define _PRMODELSPARAMETERSESTIMATION_H

#include <per/prcommon.h>

class PER_EXPORT prModelsParametersEstimation {
public:
	virtual ~prModelsParametersEstimation() = default;
};

#endif  //_PRMODELSPARAMETERSESTIMATION_H
