//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prParaboloidXML.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRPARABOLOIDXML_H)
#define _PRPARABOLOIDXML_H

#include <per/prcommon.h>
#include <per/prCameraModelXML.h>

class PER_EXPORT prParaboloidXML : public prCameraModelXML {
public:
	virtual ~prParaboloidXML() override = default;
};

#endif  //_PRPARABOLOIDXML_H
