//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prParaboloidXML.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRPARABOLOIDXML_H)
#define _PRPARABOLOIDXML_H

#include <per/prCameraModelXML.h>

class prParaboloidXML : public prCameraModelXML {
};

#endif  //_PRPARABOLOIDXML_H
