//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prPoseXML.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRPOSEXML_H)
#define _PRPOSEXML_H

#include <per/prcommon.h>
#include <per/prXML.h>

class PER_EXPORT prPoseXML : public prXML {
public:
	virtual ~prPoseXML() override = default;
};

#endif  //_PRPOSEXML_H
