git checkout devel CMakeLists.txt
git checkout devel README.md
git checkout devel config-file
git checkout devel cmake
git checkout devel doc
git checkout devel data
git checkout devel example/CMakeLists.txt
git checkout devel example/pointPerspectiveProjection
git checkout devel example/saveAndLoadStereocameraModelXML
git checkout devel example/FisheyeEquidistant2OmniCameraModelConversion
git checkout devel example/Omni2PolyCartCameraModelConversion
git checkout devel example/RationalPolynomial2PlumbBoCameraModelConversion
git checkout devel example/CartesianPolynomial2FisheyeOpenCV
git checkout devel example/RationalPolynomial2FisheyeOpenCV
git checkout devel modules/core
git checkout devel modules/estimation
git checkout devel modules/io
git checkout devel modules/sensor_pose_estimation
git checkout devel modules/features
git checkout devel modules/acquisition_representation
git checkout devel modules/CMakeLists.txt
