//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prPoseOmniOpt.h
//  @ Date : 16/01/2017
//  @ Author :
//
//


#if !defined(_PRPOSEESTIM_H)
#define _PRPOSEESTIM_H

#include <per/prcommon.h>
#include <per/prModelsParametersEstimation.h>

class PER_EXPORT prPoseEstim : public prModelsParametersEstimation {
public:
	virtual ~prPoseEstim() override = default;
};

#endif  //_PRPOSEOMNIESTIM_H
